/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.telegram;

public final class R {
    public static final class anim {
        public static final int decelerate_cubic=0x7f040000;
        public static final int icon_anim_fade_in=0x7f040001;
        public static final int icon_anim_fade_out=0x7f040002;
        public static final int scale_in=0x7f040003;
        public static final int scale_out=0x7f040004;
        public static final int slide_down=0x7f040005;
        public static final int slide_up=0x7f040006;
    }
    public static final class attr {
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraBearing=0x7f010001;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraTargetLat=0x7f010002;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraTargetLng=0x7f010003;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraTilt=0x7f010004;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraZoom=0x7f010005;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0</td><td></td></tr>
<tr><td><code>normal</code></td><td>1</td><td></td></tr>
<tr><td><code>satellite</code></td><td>2</td><td></td></tr>
<tr><td><code>terrain</code></td><td>3</td><td></td></tr>
<tr><td><code>hybrid</code></td><td>4</td><td></td></tr>
</table>
         */
        public static final int mapType=0x7f010000;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiCompass=0x7f010006;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiRotateGestures=0x7f010007;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiScrollGestures=0x7f010008;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiTiltGestures=0x7f010009;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiZoomControls=0x7f01000a;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiZoomGestures=0x7f01000b;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int useViewLifecycle=0x7f01000c;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int zOrderOnTop=0x7f01000d;
    }
    public static final class bool {
        public static final int isTablet=0x7f070000;
    }
    public static final class color {
        public static final int app_background=0x7f080000;
        public static final int background_tab_pressed=0x7f080001;
        public static final int chat_background_color=0x7f080002;
        public static final int common_action_bar_splitter=0x7f080003;
        public static final int common_signin_btn_dark_text_default=0x7f080004;
        public static final int common_signin_btn_dark_text_disabled=0x7f080005;
        public static final int common_signin_btn_dark_text_focused=0x7f080006;
        public static final int common_signin_btn_dark_text_pressed=0x7f080007;
        public static final int common_signin_btn_default_background=0x7f080008;
        public static final int common_signin_btn_light_text_default=0x7f080009;
        public static final int common_signin_btn_light_text_disabled=0x7f08000a;
        public static final int common_signin_btn_light_text_focused=0x7f08000b;
        public static final int common_signin_btn_light_text_pressed=0x7f08000c;
        public static final int common_signin_btn_text_dark=0x7f080012;
        public static final int common_signin_btn_text_light=0x7f080013;
        public static final int divider=0x7f08000d;
        public static final int gallery_background_color=0x7f08000e;
        public static final int header=0x7f08000f;
        public static final int message_bar_mic_background=0x7f080010;
        public static final int settings_background_color=0x7f080011;
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f090000;
        public static final int activity_vertical_margin=0x7f090001;
    }
    public static final class drawable {
        public static final int ab_icon_up_fixed=0x7f020000;
        public static final int ab_icon_up_gallery=0x7f020001;
        public static final int ab_icon_up_messages=0x7f020002;
        public static final int ab_progress=0x7f020003;
        public static final int addcontact_blue=0x7f020004;
        public static final int addcontact_green=0x7f020005;
        public static final int addmember=0x7f020006;
        public static final int audiocancel1=0x7f020007;
        public static final int audiocancel1_pressed=0x7f020008;
        public static final int audiocancel2=0x7f020009;
        public static final int audiocancel2_pressed=0x7f02000a;
        public static final int audioload1=0x7f02000b;
        public static final int audioload1_pressed=0x7f02000c;
        public static final int audioload2=0x7f02000d;
        public static final int audioload2_pressed=0x7f02000e;
        public static final int background_hd=0x7f02000f;
        public static final int background_tab=0x7f020010;
        public static final int bar_selector=0x7f020011;
        public static final int bar_selector_mode=0x7f020012;
        public static final int bar_selector_picker=0x7f020013;
        public static final int bar_selector_style=0x7f020014;
        public static final int bar_selector_white=0x7f020015;
        public static final int bg_emoji_bs=0x7f020016;
        public static final int bigtimer=0x7f020017;
        public static final int boxshadow=0x7f020018;
        public static final int broadcast=0x7f020019;
        public static final int broadcast2=0x7f02001a;
        public static final int broadcast3=0x7f02001b;
        public static final int broadcast4=0x7f02001c;
        public static final int broadcast_aqua=0x7f02001d;
        public static final int broadcast_blue=0x7f02001e;
        public static final int broadcast_green=0x7f02001f;
        public static final int broadcast_orange=0x7f020020;
        public static final int broadcast_pink=0x7f020021;
        public static final int broadcast_red=0x7f020022;
        public static final int broadcast_violet=0x7f020023;
        public static final int broadcast_yellow=0x7f020024;
        public static final int btn_check_off=0x7f020025;
        public static final int btn_check_off_holo_light=0x7f020026;
        public static final int btn_check_on=0x7f020027;
        public static final int btn_check_on_holo_light=0x7f020028;
        public static final int btn_down=0x7f020029;
        public static final int btn_send_location_down=0x7f02002a;
        public static final int btn_send_location_up=0x7f02002b;
        public static final int btn_up=0x7f02002c;
        public static final int btnshadow=0x7f02002d;
        public static final int burn=0x7f02002e;
        public static final int call=0x7f02002f;
        public static final int cats=0x7f020030;
        public static final int chat_incoming_media_states=0x7f020031;
        public static final int chat_incoming_text_states=0x7f020032;
        public static final int chat_outgoing_text_states=0x7f020033;
        public static final int circle=0x7f020034;
        public static final int circle1=0x7f020035;
        public static final int common_signin_btn_icon_dark=0x7f020036;
        public static final int common_signin_btn_icon_disabled_dark=0x7f020037;
        public static final int common_signin_btn_icon_disabled_focus_dark=0x7f020038;
        public static final int common_signin_btn_icon_disabled_focus_light=0x7f020039;
        public static final int common_signin_btn_icon_disabled_light=0x7f02003a;
        public static final int common_signin_btn_icon_focus_dark=0x7f02003b;
        public static final int common_signin_btn_icon_focus_light=0x7f02003c;
        public static final int common_signin_btn_icon_light=0x7f02003d;
        public static final int common_signin_btn_icon_normal_dark=0x7f02003e;
        public static final int common_signin_btn_icon_normal_light=0x7f02003f;
        public static final int common_signin_btn_icon_pressed_dark=0x7f020040;
        public static final int common_signin_btn_icon_pressed_light=0x7f020041;
        public static final int common_signin_btn_text_dark=0x7f020042;
        public static final int common_signin_btn_text_disabled_dark=0x7f020043;
        public static final int common_signin_btn_text_disabled_focus_dark=0x7f020044;
        public static final int common_signin_btn_text_disabled_focus_light=0x7f020045;
        public static final int common_signin_btn_text_disabled_light=0x7f020046;
        public static final int common_signin_btn_text_focus_dark=0x7f020047;
        public static final int common_signin_btn_text_focus_light=0x7f020048;
        public static final int common_signin_btn_text_light=0x7f020049;
        public static final int common_signin_btn_text_normal_dark=0x7f02004a;
        public static final int common_signin_btn_text_normal_light=0x7f02004b;
        public static final int common_signin_btn_text_pressed_dark=0x7f02004c;
        public static final int common_signin_btn_text_pressed_light=0x7f02004d;
        public static final int compose_panel=0x7f02004e;
        public static final int dialogs_badge=0x7f02004f;
        public static final int dialogs_check=0x7f020050;
        public static final int dialogs_halfcheck=0x7f020051;
        public static final int dialogs_warning=0x7f020052;
        public static final int doc_actions_b=0x7f020053;
        public static final int doc_actions_g=0x7f020054;
        public static final int doc_blue=0x7f020055;
        public static final int doc_green=0x7f020056;
        public static final int doccancel_b=0x7f020057;
        public static final int doccancel_g=0x7f020058;
        public static final int docload_b=0x7f020059;
        public static final int docload_g=0x7f02005a;
        public static final int docpause_b=0x7f02005b;
        public static final int docpause_g=0x7f02005c;
        public static final int edit_text=0x7f02005d;
        public static final int editheader=0x7f02005e;
        public static final int fast_thumb=0x7f02005f;
        public static final int fastscroll_thumb_default_holo=0x7f020060;
        public static final int fastscroll_thumb_pressed_holo=0x7f020061;
        public static final int gallery=0x7f020062;
        public static final int gray_button=0x7f020063;
        public static final int group_aqua=0x7f020064;
        public static final int group_blue=0x7f020065;
        public static final int group_green=0x7f020066;
        public static final int group_orange=0x7f020067;
        public static final int group_pink=0x7f020068;
        public static final int group_red=0x7f020069;
        public static final int group_violet=0x7f02006a;
        public static final int group_yellow=0x7f02006b;
        public static final int grouplist=0x7f02006c;
        public static final int header_timer=0x7f02006d;
        public static final int header_timer2=0x7f02006e;
        public static final int ic_ab_attach=0x7f02006f;
        public static final int ic_ab_back=0x7f020070;
        public static final int ic_ab_back_white=0x7f020071;
        public static final int ic_ab_compose=0x7f020072;
        public static final int ic_ab_delete_white=0x7f020073;
        public static final int ic_ab_doc=0x7f020074;
        public static final int ic_ab_done=0x7f020075;
        public static final int ic_ab_done_gray=0x7f020076;
        public static final int ic_ab_fwd_copy=0x7f020077;
        public static final int ic_ab_fwd_delete=0x7f020078;
        public static final int ic_ab_fwd_forward=0x7f020079;
        public static final int ic_ab_location=0x7f02007a;
        public static final int ic_ab_logo=0x7f02007b;
        public static final int ic_ab_new=0x7f02007c;
        public static final int ic_ab_other=0x7f02007d;
        public static final int ic_ab_other_white=0x7f02007e;
        public static final int ic_ab_other_white2=0x7f02007f;
        public static final int ic_ab_search=0x7f020080;
        public static final int ic_ab_share=0x7f020081;
        public static final int ic_ab_share_white=0x7f020082;
        public static final int ic_attach_gallery=0x7f020083;
        public static final int ic_attach_location=0x7f020084;
        public static final int ic_attach_photo=0x7f020085;
        public static final int ic_attach_video=0x7f020086;
        public static final int ic_auth_next=0x7f020087;
        public static final int ic_directory=0x7f020088;
        public static final int ic_done=0x7f020089;
        public static final int ic_edit=0x7f02008a;
        public static final int ic_emoji_backspace=0x7f02008b;
        public static final int ic_emoji_bell=0x7f02008c;
        public static final int ic_emoji_car=0x7f02008d;
        public static final int ic_emoji_flower=0x7f02008e;
        public static final int ic_emoji_recent=0x7f02008f;
        public static final int ic_emoji_smile=0x7f020090;
        public static final int ic_emoji_symbol=0x7f020091;
        public static final int ic_external_storage=0x7f020092;
        public static final int ic_gallery_background=0x7f020093;
        public static final int ic_launcher=0x7f020094;
        public static final int ic_lock_blue=0x7f020095;
        public static final int ic_lock_green=0x7f020096;
        public static final int ic_lock_white=0x7f020097;
        public static final int ic_msg_btn_cross=0x7f020098;
        public static final int ic_msg_btn_cross_custom=0x7f020099;
        public static final int ic_msg_in_cross=0x7f02009a;
        public static final int ic_msg_panel_hide=0x7f02009b;
        public static final int ic_msg_panel_kb=0x7f02009c;
        public static final int ic_msg_panel_smiles=0x7f02009d;
        public static final int ic_plusone_medium_off_client=0x7f02009e;
        public static final int ic_plusone_small_off_client=0x7f02009f;
        public static final int ic_plusone_standard_off_client=0x7f0200a0;
        public static final int ic_plusone_tall_off_client=0x7f0200a1;
        public static final int ic_profile_cross=0x7f0200a2;
        public static final int ic_profile_send_message=0x7f0200a3;
        public static final int ic_reply_icon=0x7f0200a4;
        public static final int ic_send=0x7f0200a5;
        public static final int ic_send_disabled=0x7f0200a6;
        public static final int ic_smiles_backspace=0x7f0200a7;
        public static final int ic_smiles_backspace_active=0x7f0200a8;
        public static final int ic_smiles_bell=0x7f0200a9;
        public static final int ic_smiles_bell_active=0x7f0200aa;
        public static final int ic_smiles_car=0x7f0200ab;
        public static final int ic_smiles_car_active=0x7f0200ac;
        public static final int ic_smiles_flower=0x7f0200ad;
        public static final int ic_smiles_flower_active=0x7f0200ae;
        public static final int ic_smiles_grid=0x7f0200af;
        public static final int ic_smiles_grid_active=0x7f0200b0;
        public static final int ic_smiles_recent=0x7f0200b1;
        public static final int ic_smiles_recent_active=0x7f0200b2;
        public static final int ic_smiles_smile=0x7f0200b3;
        public static final int ic_smiles_smile_active=0x7f0200b4;
        public static final int ic_storage=0x7f0200b5;
        public static final int ic_video=0x7f0200b6;
        public static final int intro1=0x7f0200b7;
        public static final int intro2=0x7f0200b8;
        public static final int intro3=0x7f0200b9;
        public static final int intro4=0x7f0200ba;
        public static final int intro5=0x7f0200bb;
        public static final int intro6=0x7f0200bc;
        public static final int intro7=0x7f0200bd;
        public static final int item_background_holo_light=0x7f0200be;
        public static final int launch_button_states=0x7f0200bf;
        public static final int list_focused_holo=0x7f0200c0;
        public static final int list_longpressed_holo_light=0x7f0200c1;
        public static final int list_pressed_holo_light=0x7f0200c2;
        public static final int list_selector=0x7f0200c3;
        public static final int list_selector_background_transition_holo_light=0x7f0200c4;
        public static final int list_selector_disabled_holo_light=0x7f0200c5;
        public static final int loading_animation=0x7f0200c6;
        public static final int location_panel=0x7f0200c7;
        public static final int location_send_button_states=0x7f0200c8;
        public static final int logout_button_states=0x7f0200c9;
        public static final int map_pin=0x7f0200ca;
        public static final int messages_list_divider=0x7f0200cb;
        public static final int messages_list_divider2=0x7f0200cc;
        public static final int mic=0x7f0200cd;
        public static final int mic_button_states=0x7f0200ce;
        public static final int mic_pressed=0x7f0200cf;
        public static final int msg_check=0x7f0200d0;
        public static final int msg_check_w=0x7f0200d1;
        public static final int msg_clock=0x7f0200d2;
        public static final int msg_clock_photo=0x7f0200d3;
        public static final int msg_halfcheck=0x7f0200d4;
        public static final int msg_halfcheck_w=0x7f0200d5;
        public static final int msg_in=0x7f0200d6;
        public static final int msg_in_photo=0x7f0200d7;
        public static final int msg_in_photo_selected=0x7f0200d8;
        public static final int msg_in_selected=0x7f0200d9;
        public static final int msg_out=0x7f0200da;
        public static final int msg_out_photo=0x7f0200db;
        public static final int msg_out_photo_selected=0x7f0200dc;
        public static final int msg_out_selected=0x7f0200dd;
        public static final int msg_warning=0x7f0200de;
        public static final int newmsg_divider=0x7f0200df;
        public static final int nophotos=0x7f0200e0;
        public static final int notification=0x7f0200e1;
        public static final int numberpicker_selection_divider=0x7f0200e2;
        public static final int p2r_progress=0x7f0200e3;
        public static final int p2r_progress_custom=0x7f0200e4;
        public static final int pagedown=0x7f0200e5;
        public static final int pause1=0x7f0200e6;
        public static final int pause1_pressed=0x7f0200e7;
        public static final int pause2=0x7f0200e8;
        public static final int pause2_pressed=0x7f0200e9;
        public static final int photo_back=0x7f0200ea;
        public static final int photo_edit_spinner=0x7f0200eb;
        public static final int photo_placeholder_in=0x7f0200ec;
        public static final int photo_placeholder_out=0x7f0200ed;
        public static final int photo_progress=0x7f0200ee;
        public static final int photo_progress_chat=0x7f0200ef;
        public static final int photo_spinner=0x7f0200f0;
        public static final int photo_spinner_normal=0x7f0200f1;
        public static final int photo_spinner_pressed=0x7f0200f2;
        public static final int photobadge=0x7f0200f3;
        public static final int photoborder=0x7f0200f4;
        public static final int photocancel=0x7f0200f5;
        public static final int photocheck=0x7f0200f6;
        public static final int photogif=0x7f0200f7;
        public static final int photoload=0x7f0200f8;
        public static final int photopause=0x7f0200f9;
        public static final int phototime=0x7f0200fa;
        public static final int photoview_placeholder=0x7f0200fb;
        public static final int play1=0x7f0200fc;
        public static final int play1_pressed=0x7f0200fd;
        public static final int play2=0x7f0200fe;
        public static final int play2_pressed=0x7f0200ff;
        public static final int player1=0x7f020100;
        public static final int player1_pressed=0x7f020101;
        public static final int player2=0x7f020102;
        public static final int player2_pressed=0x7f020103;
        public static final int playvideo=0x7f020104;
        public static final int plus=0x7f020105;
        public static final int popup_fixed=0x7f020106;
        public static final int progress_chat=0x7f020107;
        public static final int rec=0x7f020108;
        public static final int regbtn2=0x7f020109;
        public static final int regbtn2_pressed=0x7f02010a;
        public static final int regbtn_states=0x7f02010b;
        public static final int search_carret=0x7f02010c;
        public static final int search_light=0x7f02010d;
        public static final int search_light_selected=0x7f02010e;
        public static final int search_light_states=0x7f02010f;
        public static final int selectphoto_large=0x7f020110;
        public static final int selectphoto_small=0x7f020111;
        public static final int selectphoto_small_active=0x7f020112;
        public static final int selectphoto_small_grey=0x7f020113;
        public static final int shadow=0x7f020114;
        public static final int slidearrow=0x7f020115;
        public static final int spenner_pressed=0x7f020116;
        public static final int spinner=0x7f020117;
        public static final int spinner_pressed=0x7f020118;
        public static final int spinner_states=0x7f020119;
        public static final int switch_off1=0x7f02011a;
        public static final int switch_off1_pressed=0x7f02011b;
        public static final int switch_on1=0x7f02011c;
        public static final int switch_on1_pressed=0x7f02011d;
        public static final int system_black=0x7f02011e;
        public static final int system_blue=0x7f02011f;
        public static final int system_loader1=0x7f020120;
        public static final int system_loader2=0x7f020121;
        public static final int telegram_avatar=0x7f020122;
        public static final int textfield_activated=0x7f020123;
        public static final int textfield_default=0x7f020124;
        public static final int textfield_disabled=0x7f020125;
        public static final int textfield_disabled2=0x7f020126;
        public static final int textfield_focused=0x7f020127;
        public static final int tooltip=0x7f020128;
        public static final int top_pane=0x7f020129;
        public static final int top_pane_custom=0x7f02012a;
        public static final int transparent=0x7f02012b;
        public static final int user_aqua=0x7f02012c;
        public static final int user_blue=0x7f02012d;
        public static final int user_green=0x7f02012e;
        public static final int user_orange=0x7f02012f;
        public static final int user_pink=0x7f020130;
        public static final int user_placeholder=0x7f020131;
        public static final int user_red=0x7f020132;
        public static final int user_violet=0x7f020133;
        public static final int user_yellow=0x7f020134;
        public static final int video_play=0x7f020135;
        public static final int videolapse=0x7f020136;
        public static final int videotrimmer=0x7f020137;
        public static final int viewbtn=0x7f020138;
        public static final int viewbtn_pressed=0x7f020139;
        public static final int wall_selection=0x7f02013a;
    }
    public static final class id {
        public static final int HLRelativeLayout1=0x7f0c002d;
        public static final int action_progress=0x7f0c0083;
        public static final int album_count=0x7f0c0072;
        public static final int album_name=0x7f0c0071;
        public static final int audio_container=0x7f0c007a;
        public static final int back_button=0x7f0c0088;
        public static final int back_button_background=0x7f0c0087;
        public static final int background_image=0x7f0c0082;
        public static final int bottom_overlay=0x7f0c001a;
        public static final int bottom_overlay_chat=0x7f0c001c;
        public static final int bottom_overlay_chat_text=0x7f0c001d;
        public static final int bottom_overlay_text=0x7f0c001b;
        public static final int bottom_pages=0x7f0c0045;
        public static final int bubble_input_text=0x7f0c003c;
        public static final int bubble_text_view=0x7f0c0039;
        public static final int cancel_button=0x7f0c0073;
        public static final int center_progress=0x7f0c000e;
        public static final int changed_mind=0x7f0c0069;
        public static final int chat_audio_send_button=0x7f0c0019;
        public static final int chat_avatar_image=0x7f0c0006;
        public static final int chat_compose_panel=0x7f0c000b;
        public static final int chat_layout=0x7f0c0007;
        public static final int chat_list_view=0x7f0c000a;
        public static final int chat_message_text=0x7f0c0028;
        public static final int chat_send_button=0x7f0c0014;
        public static final int chat_smile_button=0x7f0c0012;
        public static final int chat_text_edit=0x7f0c0013;
        public static final int chat_timer=0x7f0c0005;
        public static final int chat_video_time=0x7f0c006c;
        public static final int color_picker=0x7f0c007f;
        public static final int compress_video=0x7f0c0098;
        public static final int contacts_button=0x7f0c004e;
        public static final int control_layout=0x7f0c0090;
        public static final int count_text=0x7f0c007b;
        public static final int docs_item_info=0x7f0c0030;
        public static final int docs_item_thumb=0x7f0c0031;
        public static final int docs_item_title=0x7f0c002f;
        public static final int docs_item_type=0x7f0c002e;
        public static final int done_button=0x7f0c003a;
        public static final int done_button_badge=0x7f0c0074;
        public static final int done_button_text=0x7f0c0075;
        public static final int edited_size=0x7f0c0097;
        public static final int edited_title=0x7f0c0096;
        public static final int empty_view=0x7f0c0008;
        public static final int first_name_field=0x7f0c0029;
        public static final int header_text=0x7f0c0046;
        public static final int hybrid=0x7f0c0000;
        public static final int icon_image1=0x7f0c0041;
        public static final int icon_image2=0x7f0c0042;
        public static final int identicon_text=0x7f0c0040;
        public static final int identicon_view=0x7f0c003f;
        public static final int image=0x7f0c0085;
        public static final int info_container=0x7f0c0093;
        public static final int info_text_view=0x7f0c0081;
        public static final int intro_view_pager=0x7f0c0043;
        public static final int invite_text=0x7f0c0033;
        public static final int last_name_field=0x7f0c002a;
        public static final int launch_background=0x7f0c0049;
        public static final int launch_button_layout=0x7f0c004a;
        public static final int launch_layout=0x7f0c0048;
        public static final int listView=0x7f0c0027;
        public static final int list_empty_view=0x7f0c006e;
        public static final int list_empty_view_text1=0x7f0c006f;
        public static final int list_empty_view_text2=0x7f0c0070;
        public static final int location_avatar_view=0x7f0c0056;
        public static final int location_bottom_view=0x7f0c0055;
        public static final int location_distance_label=0x7f0c0058;
        public static final int location_name_label=0x7f0c0057;
        public static final int location_send_button=0x7f0c0054;
        public static final int login_confirm_text=0x7f0c005d;
        public static final int login_county_code_field=0x7f0c005b;
        public static final int login_coutry_textview=0x7f0c005a;
        public static final int login_first_name_field=0x7f0c0067;
        public static final int login_last_name_field=0x7f0c0068;
        public static final int login_page1=0x7f0c0059;
        public static final int login_page2=0x7f0c005e;
        public static final int login_page3=0x7f0c0065;
        public static final int login_phone_field=0x7f0c005c;
        public static final int login_problem=0x7f0c0062;
        public static final int login_register_info=0x7f0c0066;
        public static final int login_sms_code_field=0x7f0c0060;
        public static final int login_sms_confirm_text=0x7f0c005f;
        public static final int login_time_text=0x7f0c0061;
        public static final int map_view=0x7f0c0053;
        public static final int media_grid=0x7f0c006a;
        public static final int media_photo_image=0x7f0c006b;
        public static final int message_image=0x7f0c007c;
        public static final int message_text=0x7f0c0047;
        public static final int messages_list_row_avatar=0x7f0c001f;
        public static final int messages_list_row_message=0x7f0c003d;
        public static final int messages_list_row_name=0x7f0c0020;
        public static final int messages_list_view=0x7f0c006d;
        public static final int new_broadcast_button=0x7f0c004d;
        public static final int new_group_button=0x7f0c004b;
        public static final int new_secret_button=0x7f0c004c;
        public static final int none=0x7f0c0001;
        public static final int normal=0x7f0c0002;
        public static final int original_size=0x7f0c0095;
        public static final int original_title=0x7f0c0094;
        public static final int pagedown_button=0x7f0c001e;
        public static final int parent=0x7f0c0084;
        public static final int photo_check=0x7f0c0078;
        public static final int photo_check_frame=0x7f0c0077;
        public static final int photo_frame=0x7f0c0076;
        public static final int play_button=0x7f0c008f;
        public static final int popup_container=0x7f0c007d;
        public static final int progress=0x7f0c0052;
        public static final int progressLayout=0x7f0c000c;
        public static final int progressLayoutInner=0x7f0c000d;
        public static final int record_panel=0x7f0c0015;
        public static final int recording_time_text=0x7f0c0018;
        public static final int satellite=0x7f0c0003;
        public static final int searchEmptyView=0x7f0c0009;
        public static final int secret_description1=0x7f0c0035;
        public static final int secret_description2=0x7f0c0036;
        public static final int secret_description3=0x7f0c0037;
        public static final int secret_description4=0x7f0c0038;
        public static final int secret_placeholder=0x7f0c0032;
        public static final int secret_title=0x7f0c0034;
        public static final int selection=0x7f0c0086;
        public static final int settings_avatar_image=0x7f0c0022;
        public static final int settings_button=0x7f0c004f;
        public static final int settings_call_phone=0x7f0c008c;
        public static final int settings_change_avatar_button=0x7f0c0023;
        public static final int settings_color=0x7f0c0080;
        public static final int settings_edit_name=0x7f0c0026;
        public static final int settings_name=0x7f0c0024;
        public static final int settings_online=0x7f0c0025;
        public static final int settings_row_check_button=0x7f0c003e;
        public static final int settings_row_divider=0x7f0c0021;
        public static final int settings_row_text=0x7f0c002b;
        public static final int settings_row_text_detail=0x7f0c002c;
        public static final int shadow_tablet=0x7f0c0051;
        public static final int shadow_tablet_side=0x7f0c0050;
        public static final int slideText=0x7f0c0016;
        public static final int slideToCancelTextView=0x7f0c0017;
        public static final int spinner=0x7f0c0063;
        public static final int start_messaging_button=0x7f0c0044;
        public static final int start_secret_button=0x7f0c008a;
        public static final int start_secret_button_text=0x7f0c008b;
        public static final int status_text=0x7f0c0089;
        public static final int terrain=0x7f0c0004;
        public static final int text_container=0x7f0c0079;
        public static final int text_scroll=0x7f0c007e;
        public static final int top_layout=0x7f0c003b;
        public static final int top_panel=0x7f0c000f;
        public static final int top_panel_text=0x7f0c0010;
        public static final int top_plane_close=0x7f0c0011;
        public static final int video_container=0x7f0c008d;
        public static final int video_seekbar=0x7f0c0091;
        public static final int video_timeline_view=0x7f0c0092;
        public static final int video_view=0x7f0c008e;
        public static final int wrong_number=0x7f0c0064;
    }
    public static final class layout {
        public static final int chat_header_enc_layout=0x7f030000;
        public static final int chat_header_layout=0x7f030001;
        public static final int chat_layout=0x7f030002;
        public static final int chat_loading_layout=0x7f030003;
        public static final int chat_profile_add_row=0x7f030004;
        public static final int chat_profile_avatar_layout=0x7f030005;
        public static final int chat_profile_layout=0x7f030006;
        public static final int chat_unread_layout=0x7f030007;
        public static final int contact_add_layout=0x7f030008;
        public static final int contacts_invite_row_layout=0x7f030009;
        public static final int contacts_layout=0x7f03000a;
        public static final int country_row_layout=0x7f03000b;
        public static final int country_select_layout=0x7f03000c;
        public static final int document_item=0x7f03000d;
        public static final int document_select_layout=0x7f03000e;
        public static final int empty_layout=0x7f03000f;
        public static final int encrypted_chat_placeholder=0x7f030010;
        public static final int group_create_bubble=0x7f030011;
        public static final int group_create_done_layout=0x7f030012;
        public static final int group_create_final_layout=0x7f030013;
        public static final int group_create_layout=0x7f030014;
        public static final int group_create_row_layout=0x7f030015;
        public static final int group_profile_add_member_layout=0x7f030016;
        public static final int identicon_layout=0x7f030017;
        public static final int intro_layout=0x7f030018;
        public static final int intro_layout_tablet=0x7f030019;
        public static final int intro_view_layout=0x7f03001a;
        public static final int language_select_layout=0x7f03001b;
        public static final int launch_layout_tablet=0x7f03001c;
        public static final int loading_more_layout=0x7f03001d;
        public static final int location_attach_layout=0x7f03001e;
        public static final int location_view_layout=0x7f03001f;
        public static final int login_layout=0x7f030020;
        public static final int media_layout=0x7f030021;
        public static final int media_loading_layout=0x7f030022;
        public static final int media_photo_layout=0x7f030023;
        public static final int media_video_layout=0x7f030024;
        public static final int messages_list=0x7f030025;
        public static final int photo_picker_album_layout=0x7f030026;
        public static final int photo_picker_bottom_layout=0x7f030027;
        public static final int photo_picker_layout=0x7f030028;
        public static final int photo_picker_photo_layout=0x7f030029;
        public static final int popup_audio_layout=0x7f03002a;
        public static final int popup_count_layout=0x7f03002b;
        public static final int popup_image_layout=0x7f03002c;
        public static final int popup_notification_layout=0x7f03002d;
        public static final int popup_text_layout=0x7f03002e;
        public static final int settings_blocked_users_layout=0x7f03002f;
        public static final int settings_color_dialog_layout=0x7f030030;
        public static final int settings_do_action_layout=0x7f030031;
        public static final int settings_layout=0x7f030032;
        public static final int settings_logout_button=0x7f030033;
        public static final int settings_name_layout=0x7f030034;
        public static final int settings_row_button_layout=0x7f030035;
        public static final int settings_row_check_layout=0x7f030036;
        public static final int settings_row_check_notify_layout=0x7f030037;
        public static final int settings_row_color_layout=0x7f030038;
        public static final int settings_row_detail_layout=0x7f030039;
        public static final int settings_row_version=0x7f03003a;
        public static final int settings_unblock_info_row_layout=0x7f03003b;
        public static final int settings_wallpapers_layout=0x7f03003c;
        public static final int settings_wallpapers_my_row=0x7f03003d;
        public static final int settings_wallpapers_other_row=0x7f03003e;
        public static final int updating_state_layout=0x7f03003f;
        public static final int user_profile_avatar_layout=0x7f030040;
        public static final int user_profile_identicon_layout=0x7f030041;
        public static final int user_profile_layout=0x7f030042;
        public static final int user_profile_leftright_row_layout=0x7f030043;
        public static final int user_profile_phone_layout=0x7f030044;
        public static final int video_editor_layout=0x7f030045;
    }
    public static final class raw {
        public static final int sound_a=0x7f060000;
    }
    public static final class string {
        public static final int AccessError=0x7f0a0000;
        public static final int ActionAddUser=0x7f0a0001;
        public static final int ActionAddUserYou=0x7f0a0002;
        public static final int ActionChangedPhoto=0x7f0a0003;
        public static final int ActionChangedTitle=0x7f0a0004;
        public static final int ActionCreateGroup=0x7f0a0005;
        public static final int ActionKickUser=0x7f0a0006;
        public static final int ActionKickUserYou=0x7f0a0007;
        public static final int ActionLeftUser=0x7f0a0008;
        public static final int ActionRemovedPhoto=0x7f0a0009;
        public static final int ActionTakeScreenshoot=0x7f0a000a;
        public static final int ActionTakeScreenshootYou=0x7f0a000b;
        public static final int ActionYouAddUser=0x7f0a000c;
        public static final int ActionYouChangedPhoto=0x7f0a000d;
        public static final int ActionYouChangedTitle=0x7f0a000e;
        public static final int ActionYouCreateGroup=0x7f0a000f;
        public static final int ActionYouKickUser=0x7f0a0010;
        public static final int ActionYouLeftUser=0x7f0a0011;
        public static final int ActionYouRemovedPhoto=0x7f0a0012;
        public static final int Add=0x7f0a0013;
        public static final int AddContact=0x7f0a0014;
        public static final int AddContactQ=0x7f0a0015;
        public static final int AddMember=0x7f0a0016;
        public static final int AddRecipient=0x7f0a0017;
        public static final int AddToContacts=0x7f0a0018;
        public static final int AddToTheGroup=0x7f0a0019;
        public static final int Alert=0x7f0a001a;
        public static final int AllContacts=0x7f0a001b;
        public static final int AllPhotos=0x7f0a001c;
        public static final int AlwaysShowPopup=0x7f0a001d;
        public static final int AndMoreTyping_few=0x7f0a001e;
        public static final int AndMoreTyping_many=0x7f0a001f;
        public static final int AndMoreTyping_one=0x7f0a0020;
        public static final int AndMoreTyping_other=0x7f0a0021;
        public static final int AndMoreTyping_two=0x7f0a0022;
        public static final int AndMoreTyping_zero=0x7f0a0023;
        public static final int AppName=0x7f0a0024;
        public static final int ApplyLocalizationFile=0x7f0a0025;
        public static final int AppsgeyserId=0x7f0a0026;
        public static final int AreTyping=0x7f0a0027;
        public static final int AreYouSure=0x7f0a0028;
        public static final int AreYouSureBlockContact=0x7f0a0029;
        public static final int AreYouSureDeleteAndExit=0x7f0a002a;
        public static final int AreYouSureDeleteContact=0x7f0a002b;
        public static final int AreYouSureDeleteThisChat=0x7f0a002c;
        public static final int AreYouSureLogout=0x7f0a002d;
        public static final int AreYouSureSecretChat=0x7f0a002e;
        public static final int AreYouSureSessions=0x7f0a002f;
        public static final int AreYouSureShareMyContactInfo=0x7f0a0030;
        public static final int AreYouSureUnblockContact=0x7f0a0031;
        public static final int AskAQuestion=0x7f0a0032;
        public static final int AskAQuestionInfo=0x7f0a0033;
        public static final int AskButton=0x7f0a0034;
        public static final int Attach=0x7f0a0035;
        public static final int AttachAudio=0x7f0a0036;
        public static final int AttachContact=0x7f0a0037;
        public static final int AttachDocument=0x7f0a0038;
        public static final int AttachLocation=0x7f0a0039;
        public static final int AttachPhoto=0x7f0a003a;
        public static final int AttachVideo=0x7f0a003b;
        public static final int AutomaticMediaDownload=0x7f0a003c;
        public static final int AwaitingEncryption=0x7f0a003d;
        public static final int Back=0x7f0a003e;
        public static final int BadgeNumber=0x7f0a003f;
        public static final int BlockContact=0x7f0a0040;
        public static final int BlockedUsers=0x7f0a0041;
        public static final int BroadcastList=0x7f0a0042;
        public static final int Call=0x7f0a0043;
        public static final int CallText=0x7f0a0044;
        public static final int Calling=0x7f0a0045;
        public static final int Cancel=0x7f0a0046;
        public static final int CancelDownload=0x7f0a0047;
        public static final int CancelRegistration=0x7f0a0048;
        public static final int ChatBackground=0x7f0a0049;
        public static final int ChatDocument=0x7f0a004a;
        public static final int ChatGallery=0x7f0a004b;
        public static final int ChatLocation=0x7f0a004c;
        public static final int ChatTakePhoto=0x7f0a004d;
        public static final int ChatVideo=0x7f0a004e;
        public static final int Chats=0x7f0a004f;
        public static final int ChooseCountry=0x7f0a0050;
        public static final int ClearHistory=0x7f0a0051;
        public static final int Code=0x7f0a0052;
        public static final int CodeExpired=0x7f0a0053;
        public static final int CompatibilityChat=0x7f0a0054;
        public static final int CompressVideo=0x7f0a0055;
        public static final int Connecting=0x7f0a0056;
        public static final int ContactInfo=0x7f0a0057;
        public static final int ContactJoined=0x7f0a0058;
        public static final int Contacts=0x7f0a0059;
        public static final int Copy=0x7f0a005a;
        public static final int CreateEncryptedChatError=0x7f0a005b;
        public static final int DOWNLOAD=0x7f0a005c;
        public static final int Days_few=0x7f0a005d;
        public static final int Days_many=0x7f0a005e;
        public static final int Days_one=0x7f0a005f;
        public static final int Days_other=0x7f0a0060;
        public static final int Days_two=0x7f0a0061;
        public static final int Days_zero=0x7f0a0062;
        public static final int Default=0x7f0a0063;
        public static final int Delete=0x7f0a0064;
        public static final int DeleteAndExit=0x7f0a0065;
        public static final int DeleteChat=0x7f0a0066;
        public static final int DeleteChatQuestion=0x7f0a0067;
        public static final int DeleteContact=0x7f0a0068;
        public static final int DeleteLocalization=0x7f0a0069;
        public static final int DeletePhoto=0x7f0a006a;
        public static final int DeleteThisChat=0x7f0a006b;
        public static final int DeleteThisGroup=0x7f0a006c;
        public static final int DidNotGetTheCode=0x7f0a006d;
        public static final int Disabled=0x7f0a006e;
        public static final int Done=0x7f0a006f;
        public static final int Edit=0x7f0a0070;
        public static final int EditContact=0x7f0a0071;
        public static final int EditVideo=0x7f0a0072;
        public static final int EditedVideo=0x7f0a0073;
        public static final int EnableAnimations=0x7f0a0074;
        public static final int Enabled=0x7f0a0075;
        public static final int EncryptedChatAccepted=0x7f0a0076;
        public static final int EncryptedChatRequested=0x7f0a0077;
        public static final int EncryptedChatStartedIncoming=0x7f0a0078;
        public static final int EncryptedChatStartedOutgoing=0x7f0a0079;
        public static final int EncryptedDescription1=0x7f0a007a;
        public static final int EncryptedDescription2=0x7f0a007b;
        public static final int EncryptedDescription3=0x7f0a007c;
        public static final int EncryptedDescription4=0x7f0a007d;
        public static final int EncryptedDescriptionTitle=0x7f0a007e;
        public static final int EncryptedPlaceholderTitleIncoming=0x7f0a007f;
        public static final int EncryptedPlaceholderTitleOutgoing=0x7f0a0080;
        public static final int EncryptionKey=0x7f0a0081;
        public static final int EncryptionKeyDescription=0x7f0a0082;
        public static final int EncryptionProcessing=0x7f0a0083;
        public static final int EncryptionRejected=0x7f0a0084;
        public static final int EnterGroupNamePlaceholder=0x7f0a0085;
        public static final int EnterGroupNameTitle=0x7f0a0086;
        public static final int EnterListName=0x7f0a0087;
        public static final int ErrorOccurred=0x7f0a0088;
        public static final int Events=0x7f0a0089;
        public static final int ExternalStorage=0x7f0a008a;
        public static final int FeatureUnavailable=0x7f0a008b;
        public static final int FileUploadLimit=0x7f0a008c;
        public static final int FirstName=0x7f0a008d;
        public static final int FloodWait=0x7f0a008e;
        public static final int Forward=0x7f0a008f;
        public static final int ForwardFromMyName=0x7f0a0090;
        public static final int ForwardMessagesTo=0x7f0a0091;
        public static final int ForwardMessagesToGroup=0x7f0a0092;
        public static final int ForwardedMessage=0x7f0a0093;
        public static final int FreeOfTotal=0x7f0a0094;
        public static final int From=0x7f0a0095;
        public static final int FromCamera=0x7f0a0096;
        public static final int FromContacts_few=0x7f0a0097;
        public static final int FromContacts_many=0x7f0a0098;
        public static final int FromContacts_one=0x7f0a0099;
        public static final int FromContacts_other=0x7f0a009a;
        public static final int FromContacts_two=0x7f0a009b;
        public static final int FromContacts_zero=0x7f0a009c;
        public static final int FromGalley=0x7f0a009d;
        public static final int FromYou=0x7f0a009e;
        public static final int Gallery=0x7f0a009f;
        public static final int GlobalSearch=0x7f0a00a0;
        public static final int GotAQuestion=0x7f0a00a1;
        public static final int GroupInfo=0x7f0a00a2;
        public static final int GroupName=0x7f0a00a3;
        public static final int GroupNotifications=0x7f0a00a4;
        public static final int HiddenName=0x7f0a00a5;
        public static final int Hours_few=0x7f0a00a6;
        public static final int Hours_many=0x7f0a00a7;
        public static final int Hours_one=0x7f0a00a8;
        public static final int Hours_other=0x7f0a00a9;
        public static final int Hours_two=0x7f0a00aa;
        public static final int Hours_zero=0x7f0a00ab;
        public static final int Hybrid=0x7f0a00ac;
        public static final int ImportContacts=0x7f0a00ad;
        public static final int InAppNotifications=0x7f0a00ae;
        public static final int InAppPreview=0x7f0a00af;
        public static final int InAppSounds=0x7f0a00b0;
        public static final int InAppVibrate=0x7f0a00b1;
        public static final int IncorrectLocalization=0x7f0a00b2;
        public static final int Info=0x7f0a00b3;
        public static final int InternalStorage=0x7f0a00b4;
        public static final int InvalidCode=0x7f0a00b5;
        public static final int InvalidFirstName=0x7f0a00b6;
        public static final int InvalidLastName=0x7f0a00b7;
        public static final int InvalidPhoneNumber=0x7f0a00b8;
        public static final int Invisible=0x7f0a00b9;
        public static final int InviteFriends=0x7f0a00ba;
        public static final int InviteText=0x7f0a00bb;
        public static final int InviteUser=0x7f0a00bc;
        public static final int IsTyping=0x7f0a00bd;
        public static final int KMetersAway=0x7f0a00be;
        public static final int KickFromBroadcast=0x7f0a00bf;
        public static final int KickFromGroup=0x7f0a00c0;
        public static final int Language=0x7f0a00c1;
        public static final int LanguageCode=0x7f0a00c2;
        public static final int LanguageName=0x7f0a00c3;
        public static final int LanguageNameInEnglish=0x7f0a00c4;
        public static final int LastName=0x7f0a00c5;
        public static final int LastSeen=0x7f0a00c6;
        public static final int LastSeenDate=0x7f0a00c7;
        public static final int LedColor=0x7f0a00c8;
        public static final int Loading=0x7f0a00c9;
        public static final int LogOut=0x7f0a00ca;
        public static final int Long=0x7f0a00cb;
        public static final int Map=0x7f0a00cc;
        public static final int MembersCount=0x7f0a00cd;
        public static final int Members_few=0x7f0a00ce;
        public static final int Members_many=0x7f0a00cf;
        public static final int Members_one=0x7f0a00d0;
        public static final int Members_other=0x7f0a00d1;
        public static final int Members_two=0x7f0a00d2;
        public static final int Members_zero=0x7f0a00d3;
        public static final int Message=0x7f0a00d4;
        public static final int MessageLifetime=0x7f0a00d5;
        public static final int MessageLifetimeChanged=0x7f0a00d6;
        public static final int MessageLifetimeChangedOutgoing=0x7f0a00d7;
        public static final int MessageLifetimeRemoved=0x7f0a00d8;
        public static final int MessageLifetimeYouRemoved=0x7f0a00d9;
        public static final int MessageNotifications=0x7f0a00da;
        public static final int MessagePreview=0x7f0a00db;
        public static final int MessagesSettings=0x7f0a00dc;
        public static final int MetersAway=0x7f0a00dd;
        public static final int Minutes_few=0x7f0a00de;
        public static final int Minutes_many=0x7f0a00df;
        public static final int Minutes_one=0x7f0a00e0;
        public static final int Minutes_other=0x7f0a00e1;
        public static final int Minutes_two=0x7f0a00e2;
        public static final int Minutes_zero=0x7f0a00e3;
        public static final int MyLocation=0x7f0a00e4;
        public static final int NewBroadcastList=0x7f0a00e5;
        public static final int NewGroup=0x7f0a00e6;
        public static final int NewMessages=0x7f0a00e7;
        public static final int NewMessages_few=0x7f0a00e8;
        public static final int NewMessages_many=0x7f0a00e9;
        public static final int NewMessages_one=0x7f0a00ea;
        public static final int NewMessages_other=0x7f0a00eb;
        public static final int NewMessages_two=0x7f0a00ec;
        public static final int NewMessages_zero=0x7f0a00ed;
        public static final int NewSecretChat=0x7f0a00ee;
        public static final int Next=0x7f0a00ef;
        public static final int NoBlocked=0x7f0a00f0;
        public static final int NoChats=0x7f0a00f1;
        public static final int NoChatsHelp=0x7f0a00f2;
        public static final int NoContacts=0x7f0a00f3;
        public static final int NoFiles=0x7f0a00f4;
        public static final int NoHandleAppInstalled=0x7f0a00f5;
        public static final int NoMailInstalled=0x7f0a00f6;
        public static final int NoMedia=0x7f0a00f7;
        public static final int NoMediaAutoDownload=0x7f0a00f8;
        public static final int NoMessages=0x7f0a00f9;
        public static final int NoPhotos=0x7f0a00fa;
        public static final int NoPlayerInstalled=0x7f0a00fb;
        public static final int NoPopup=0x7f0a00fc;
        public static final int NoRecent=0x7f0a00fd;
        public static final int NoResult=0x7f0a00fe;
        public static final int NoSound=0x7f0a00ff;
        public static final int NotMounted=0x7f0a0100;
        public static final int NotificationContactJoined=0x7f0a0101;
        public static final int NotificationContactNewPhoto=0x7f0a0102;
        public static final int NotificationEditedGroupName=0x7f0a0103;
        public static final int NotificationEditedGroupPhoto=0x7f0a0104;
        public static final int NotificationGroupAddMember=0x7f0a0105;
        public static final int NotificationGroupKickMember=0x7f0a0106;
        public static final int NotificationGroupKickYou=0x7f0a0107;
        public static final int NotificationGroupLeftMember=0x7f0a0108;
        public static final int NotificationInvitedToGroup=0x7f0a0109;
        public static final int NotificationMessageAudio=0x7f0a010a;
        public static final int NotificationMessageContact=0x7f0a010b;
        public static final int NotificationMessageDocument=0x7f0a010c;
        public static final int NotificationMessageGroupAudio=0x7f0a010d;
        public static final int NotificationMessageGroupContact=0x7f0a010e;
        public static final int NotificationMessageGroupDocument=0x7f0a010f;
        public static final int NotificationMessageGroupMap=0x7f0a0110;
        public static final int NotificationMessageGroupNoText=0x7f0a0111;
        public static final int NotificationMessageGroupPhoto=0x7f0a0112;
        public static final int NotificationMessageGroupText=0x7f0a0113;
        public static final int NotificationMessageGroupVideo=0x7f0a0114;
        public static final int NotificationMessageMap=0x7f0a0115;
        public static final int NotificationMessageNoText=0x7f0a0116;
        public static final int NotificationMessagePhoto=0x7f0a0117;
        public static final int NotificationMessageText=0x7f0a0118;
        public static final int NotificationMessageVideo=0x7f0a0119;
        public static final int NotificationMessagesPeopleDisplayOrder=0x7f0a011a;
        public static final int NotificationUnrecognizedDevice=0x7f0a011b;
        public static final int Notifications=0x7f0a011c;
        public static final int NotificationsAndSounds=0x7f0a011d;
        public static final int NotificationsService=0x7f0a011e;
        public static final int NotificationsServiceDisableInfo=0x7f0a011f;
        public static final int NumberUnknown=0x7f0a0120;
        public static final int OK=0x7f0a0121;
        public static final int Of=0x7f0a0122;
        public static final int Offline=0x7f0a0123;
        public static final int Online=0x7f0a0124;
        public static final int Online_few=0x7f0a0125;
        public static final int Online_many=0x7f0a0126;
        public static final int Online_one=0x7f0a0127;
        public static final int Online_other=0x7f0a0128;
        public static final int Online_two=0x7f0a0129;
        public static final int Online_zero=0x7f0a012a;
        public static final int OnlyWhenScreenOff=0x7f0a012b;
        public static final int OnlyWhenScreenOn=0x7f0a012c;
        public static final int Open=0x7f0a012d;
        public static final int OpenPhoto=0x7f0a012e;
        public static final int OriginalVideo=0x7f0a012f;
        public static final int PHONE=0x7f0a0130;
        public static final int Page1Message=0x7f0a0131;
        public static final int Page1Title=0x7f0a0132;
        public static final int Page2Message=0x7f0a0133;
        public static final int Page2Title=0x7f0a0134;
        public static final int Page3Message=0x7f0a0135;
        public static final int Page3Title=0x7f0a0136;
        public static final int Page4Message=0x7f0a0137;
        public static final int Page4Title=0x7f0a0138;
        public static final int Page5Message=0x7f0a0139;
        public static final int Page5Title=0x7f0a013a;
        public static final int Page6Message=0x7f0a013b;
        public static final int Page6Title=0x7f0a013c;
        public static final int Page7Message=0x7f0a013d;
        public static final int Page7Title=0x7f0a013e;
        public static final int Pebble=0x7f0a013f;
        public static final int Phone=0x7f0a0140;
        public static final int PhoneHome=0x7f0a0141;
        public static final int PhoneMain=0x7f0a0142;
        public static final int PhoneMobile=0x7f0a0143;
        public static final int PhoneOther=0x7f0a0144;
        public static final int PhoneWork=0x7f0a0145;
        public static final int PhotoTip=0x7f0a0146;
        public static final int PopupNotification=0x7f0a0147;
        public static final int RegisterText=0x7f0a0148;
        public static final int Reply=0x7f0a0149;
        public static final int ReplyToGroup=0x7f0a014a;
        public static final int ReplyToUser=0x7f0a014b;
        public static final int Reset=0x7f0a014c;
        public static final int ResetAllNotifications=0x7f0a014d;
        public static final int ResetNotificationsText=0x7f0a014e;
        public static final int Retry=0x7f0a014f;
        public static final int SETTINGS=0x7f0a0150;
        public static final int SHAREDMEDIA=0x7f0a0151;
        public static final int Satellite=0x7f0a0152;
        public static final int SaveIncomingPhotos=0x7f0a0153;
        public static final int SaveToDownloads=0x7f0a0154;
        public static final int SaveToGallery=0x7f0a0155;
        public static final int SaveToGallerySettings=0x7f0a0156;
        public static final int SdCard=0x7f0a0157;
        public static final int Search=0x7f0a0158;
        public static final int Seconds_few=0x7f0a0159;
        public static final int Seconds_many=0x7f0a015a;
        public static final int Seconds_one=0x7f0a015b;
        public static final int Seconds_other=0x7f0a015c;
        public static final int Seconds_two=0x7f0a015d;
        public static final int Seconds_zero=0x7f0a015e;
        public static final int SecretTitle=0x7f0a015f;
        public static final int SelectChat=0x7f0a0160;
        public static final int SelectContact=0x7f0a0161;
        public static final int SelectFile=0x7f0a0162;
        public static final int Selected=0x7f0a0163;
        public static final int Send=0x7f0a0164;
        public static final int SendByEnter=0x7f0a0165;
        public static final int SendLocation=0x7f0a0166;
        public static final int SendMessageTo=0x7f0a0167;
        public static final int SendMessagesTo=0x7f0a0168;
        public static final int SendMessagesToGroup=0x7f0a0169;
        public static final int SendingVideo=0x7f0a016a;
        public static final int SentSmsCode=0x7f0a016b;
        public static final int Set=0x7f0a016c;
        public static final int Settings=0x7f0a016d;
        public static final int SettingsDefault=0x7f0a016e;
        public static final int ShareContact=0x7f0a016f;
        public static final int ShareLocation=0x7f0a0170;
        public static final int ShareMyContactInfo=0x7f0a0171;
        public static final int SharedMedia=0x7f0a0172;
        public static final int Short=0x7f0a0173;
        public static final int ShortMessageLifetimeForever=0x7f0a0174;
        public static final int ShowAllMedia=0x7f0a0175;
        public static final int SlideToCancel=0x7f0a0176;
        public static final int SortBy=0x7f0a0177;
        public static final int SortFirstName=0x7f0a0178;
        public static final int SortLastName=0x7f0a0179;
        public static final int Sound=0x7f0a017a;
        public static final int StartEncryptedChat=0x7f0a017b;
        public static final int StartMessaging=0x7f0a017c;
        public static final int StartText=0x7f0a017d;
        public static final int Support=0x7f0a017e;
        public static final int SystemDefault=0x7f0a017f;
        public static final int SystemRoot=0x7f0a0180;
        public static final int TelegramFaq=0x7f0a0181;
        public static final int TelegramFaqUrl=0x7f0a0182;
        public static final int TerminateAllSessions=0x7f0a0183;
        public static final int TextSize=0x7f0a0184;
        public static final int TodayAt=0x7f0a0185;
        public static final int TypeMessage=0x7f0a0186;
        public static final int Typing=0x7f0a0187;
        public static final int Unblock=0x7f0a0188;
        public static final int UnblockText=0x7f0a0189;
        public static final int UndoAllCustom=0x7f0a018a;
        public static final int UnknownError=0x7f0a018b;
        public static final int UnsupportedAttachment=0x7f0a018c;
        public static final int UnsuppotedMedia=0x7f0a018d;
        public static final int Updating=0x7f0a018e;
        public static final int UsbActive=0x7f0a018f;
        public static final int Username=0x7f0a0190;
        public static final int UsernameAvailable=0x7f0a0191;
        public static final int UsernameChecking=0x7f0a0192;
        public static final int UsernameEmpty=0x7f0a0193;
        public static final int UsernameHelp=0x7f0a0194;
        public static final int UsernameInUse=0x7f0a0195;
        public static final int UsernameInvalid=0x7f0a0196;
        public static final int UsernameInvalidLong=0x7f0a0197;
        public static final int UsernameInvalidShort=0x7f0a0198;
        public static final int UsernameInvalidStartNumber=0x7f0a0199;
        public static final int UsernamePlaceholder=0x7f0a019a;
        public static final int Vibrate=0x7f0a019b;
        public static final int ViewLocation=0x7f0a019c;
        public static final int ViewPhoto=0x7f0a019d;
        public static final int ViewVideo=0x7f0a019e;
        public static final int WaitingForNetwork=0x7f0a019f;
        public static final int Weeks_few=0x7f0a01a0;
        public static final int Weeks_many=0x7f0a01a1;
        public static final int Weeks_one=0x7f0a01a2;
        public static final int Weeks_other=0x7f0a01a3;
        public static final int Weeks_two=0x7f0a01a4;
        public static final int Weeks_zero=0x7f0a01a5;
        public static final int WhenConnectedOnWiFi=0x7f0a01a6;
        public static final int WhenRoaming=0x7f0a01a7;
        public static final int WhenUsingMobileData=0x7f0a01a8;
        public static final int WiFiOnly=0x7f0a01a9;
        public static final int WrongCountry=0x7f0a01aa;
        public static final int WrongNumber=0x7f0a01ab;
        public static final int Yesterday=0x7f0a01ac;
        public static final int YesterdayAt=0x7f0a01ad;
        public static final int YouCreatedBroadcastList=0x7f0a01ae;
        public static final int YouHaveNewMessage=0x7f0a01af;
        public static final int YouLeft=0x7f0a01b0;
        public static final int YouWereKicked=0x7f0a01b1;
        public static final int YourCode=0x7f0a01b2;
        public static final int YourFirstNameAndLastName=0x7f0a01b3;
        public static final int YourName=0x7f0a01b4;
        public static final int YourPhone=0x7f0a01b5;
        public static final int auth_client_needs_enabling_title=0x7f0a01b6;
        public static final int auth_client_needs_installation_title=0x7f0a01b7;
        public static final int auth_client_needs_update_title=0x7f0a01b8;
        public static final int auth_client_play_services_err_notification_msg=0x7f0a01b9;
        public static final int auth_client_requested_by_msg=0x7f0a01ba;
        public static final int auth_client_using_bad_version_title=0x7f0a01bb;
        public static final int chatDate=0x7f0a01bc;
        public static final int chatFullDate=0x7f0a01bd;
        public static final int common_google_play_services_enable_button=0x7f0a01be;
        public static final int common_google_play_services_enable_text=0x7f0a01bf;
        public static final int common_google_play_services_enable_title=0x7f0a01c0;
        public static final int common_google_play_services_install_button=0x7f0a01c1;
        public static final int common_google_play_services_install_text_phone=0x7f0a01c2;
        public static final int common_google_play_services_install_text_tablet=0x7f0a01c3;
        public static final int common_google_play_services_install_title=0x7f0a01c4;
        public static final int common_google_play_services_invalid_account_text=0x7f0a01c5;
        public static final int common_google_play_services_invalid_account_title=0x7f0a01c6;
        public static final int common_google_play_services_network_error_text=0x7f0a01c7;
        public static final int common_google_play_services_network_error_title=0x7f0a01c8;
        public static final int common_google_play_services_unknown_issue=0x7f0a01c9;
        public static final int common_google_play_services_unsupported_text=0x7f0a01ca;
        public static final int common_google_play_services_unsupported_title=0x7f0a01cb;
        public static final int common_google_play_services_update_button=0x7f0a01cc;
        public static final int common_google_play_services_update_text=0x7f0a01cd;
        public static final int common_google_play_services_update_title=0x7f0a01ce;
        public static final int common_signin_button_text=0x7f0a01cf;
        public static final int common_signin_button_text_long=0x7f0a01d0;
        public static final int formatDateAtTime=0x7f0a01d1;
        public static final int formatterDay12H=0x7f0a01d2;
        public static final int formatterDay24H=0x7f0a01d3;
        public static final int formatterMonth=0x7f0a01d4;
        public static final int formatterWeek=0x7f0a01d5;
        public static final int formatterYear=0x7f0a01d6;
        public static final int formatterYearMax=0x7f0a01d7;
        public static final int messages_few=0x7f0a01d8;
        public static final int messages_many=0x7f0a01d9;
        public static final int messages_one=0x7f0a01da;
        public static final int messages_other=0x7f0a01db;
        public static final int messages_two=0x7f0a01dc;
        public static final int messages_zero=0x7f0a01dd;
    }
    public static final class style {
        public static final int ActionBar_Transparent_TMessages_Item=0x7f0b0000;
        public static final int ActionBar_Transparent_TMessages_Start=0x7f0b0001;
        public static final int Theme_TMessages=0x7f0b0002;
        public static final int Theme_TMessages_EditText=0x7f0b0003;
        public static final int Theme_TMessages_ListView=0x7f0b0004;
        public static final int Theme_TMessages_PopupNotification=0x7f0b0005;
        public static final int Theme_TMessages_Start=0x7f0b0006;
    }
    public static final class xml {
        public static final int auth=0x7f050000;
        public static final int auth_menu=0x7f050001;
        public static final int contacts=0x7f050002;
        public static final int sync_contacts=0x7f050003;
    }
    public static final class styleable {
        /** Attributes that can be used with a MapAttrs.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #MapAttrs_cameraBearing org.telegram.messenger:cameraBearing}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_cameraTargetLat org.telegram.messenger:cameraTargetLat}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_cameraTargetLng org.telegram.messenger:cameraTargetLng}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_cameraTilt org.telegram.messenger:cameraTilt}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_cameraZoom org.telegram.messenger:cameraZoom}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_mapType org.telegram.messenger:mapType}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiCompass org.telegram.messenger:uiCompass}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiRotateGestures org.telegram.messenger:uiRotateGestures}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiScrollGestures org.telegram.messenger:uiScrollGestures}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiTiltGestures org.telegram.messenger:uiTiltGestures}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiZoomControls org.telegram.messenger:uiZoomControls}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiZoomGestures org.telegram.messenger:uiZoomGestures}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_useViewLifecycle org.telegram.messenger:useViewLifecycle}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_zOrderOnTop org.telegram.messenger:zOrderOnTop}</code></td><td></td></tr>
           </table>
           @see #MapAttrs_cameraBearing
           @see #MapAttrs_cameraTargetLat
           @see #MapAttrs_cameraTargetLng
           @see #MapAttrs_cameraTilt
           @see #MapAttrs_cameraZoom
           @see #MapAttrs_mapType
           @see #MapAttrs_uiCompass
           @see #MapAttrs_uiRotateGestures
           @see #MapAttrs_uiScrollGestures
           @see #MapAttrs_uiTiltGestures
           @see #MapAttrs_uiZoomControls
           @see #MapAttrs_uiZoomGestures
           @see #MapAttrs_useViewLifecycle
           @see #MapAttrs_zOrderOnTop
         */
        public static final int[] MapAttrs = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005, 0x7f010006, 0x7f010007,
            0x7f010008, 0x7f010009, 0x7f01000a, 0x7f01000b,
            0x7f01000c, 0x7f01000d
        };
        /**
          <p>This symbol is the offset where the {@link org.telegram.R.attr#cameraBearing}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.telegram.messenger:cameraBearing
        */
        public static final int MapAttrs_cameraBearing = 1;
        /**
          <p>This symbol is the offset where the {@link org.telegram.R.attr#cameraTargetLat}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.telegram.messenger:cameraTargetLat
        */
        public static final int MapAttrs_cameraTargetLat = 2;
        /**
          <p>This symbol is the offset where the {@link org.telegram.R.attr#cameraTargetLng}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.telegram.messenger:cameraTargetLng
        */
        public static final int MapAttrs_cameraTargetLng = 3;
        /**
          <p>This symbol is the offset where the {@link org.telegram.R.attr#cameraTilt}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.telegram.messenger:cameraTilt
        */
        public static final int MapAttrs_cameraTilt = 4;
        /**
          <p>This symbol is the offset where the {@link org.telegram.R.attr#cameraZoom}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.telegram.messenger:cameraZoom
        */
        public static final int MapAttrs_cameraZoom = 5;
        /**
          <p>This symbol is the offset where the {@link org.telegram.R.attr#mapType}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0</td><td></td></tr>
<tr><td><code>normal</code></td><td>1</td><td></td></tr>
<tr><td><code>satellite</code></td><td>2</td><td></td></tr>
<tr><td><code>terrain</code></td><td>3</td><td></td></tr>
<tr><td><code>hybrid</code></td><td>4</td><td></td></tr>
</table>
          @attr name org.telegram.messenger:mapType
        */
        public static final int MapAttrs_mapType = 0;
        /**
          <p>This symbol is the offset where the {@link org.telegram.R.attr#uiCompass}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.telegram.messenger:uiCompass
        */
        public static final int MapAttrs_uiCompass = 6;
        /**
          <p>This symbol is the offset where the {@link org.telegram.R.attr#uiRotateGestures}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.telegram.messenger:uiRotateGestures
        */
        public static final int MapAttrs_uiRotateGestures = 7;
        /**
          <p>This symbol is the offset where the {@link org.telegram.R.attr#uiScrollGestures}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.telegram.messenger:uiScrollGestures
        */
        public static final int MapAttrs_uiScrollGestures = 8;
        /**
          <p>This symbol is the offset where the {@link org.telegram.R.attr#uiTiltGestures}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.telegram.messenger:uiTiltGestures
        */
        public static final int MapAttrs_uiTiltGestures = 9;
        /**
          <p>This symbol is the offset where the {@link org.telegram.R.attr#uiZoomControls}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.telegram.messenger:uiZoomControls
        */
        public static final int MapAttrs_uiZoomControls = 10;
        /**
          <p>This symbol is the offset where the {@link org.telegram.R.attr#uiZoomGestures}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.telegram.messenger:uiZoomGestures
        */
        public static final int MapAttrs_uiZoomGestures = 11;
        /**
          <p>This symbol is the offset where the {@link org.telegram.R.attr#useViewLifecycle}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.telegram.messenger:useViewLifecycle
        */
        public static final int MapAttrs_useViewLifecycle = 12;
        /**
          <p>This symbol is the offset where the {@link org.telegram.R.attr#zOrderOnTop}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.telegram.messenger:zOrderOnTop
        */
        public static final int MapAttrs_zOrderOnTop = 13;
    };
}
